### ISSUE TITLE
Bug: Missing "validations"

### ISSUE THREAD

**Issue by IlyaTheSawmill** [happer64bit/github-issue-template-generator#8]
### Web Browser

Chrome

### Describe the error

the correct format is:
```
validations:
      required: true
```

but it generates only `required: true`, no `validations:`

**Comment by wintkhantlin** [comment]
@IlyaYezelovsky This Issue was resolved now! Thanks for your feedback

**Comment by IlyaTheSawmill** [comment]
the error seems still appears
maybe the correct is that, `validations` is not under `attributes`
```
attributes:
      label: 114514
validations:
        required: true
```

**Comment by wintkhantlin** [comment]
Thanks!! The issue is now solved
